language: node_js

notifications:
  email:
    - medikoo+next-tick@medikoo.com

jobs:
  include:
    - stage: lint
      node_js:
        - 0.12
        - 4
        - 6
        - 8
        - 10
      script: npm run lint
    - stage: test
      node_js: 8
      script: npm test
