language: node_js
node_js:
  - 0.12
  - 4
  - 6
  - 8
  - 10

notifications:
  email:
    - medikoo+next-tick@medikoo.com

jobs:
  include:
    - stage: lint
      node_js: 8
      script: npm run lint
    - stage: test
      script: npm test
